all: simple_quicksort examples

simple_quicksort: simple_quicksort.c
	gcc simple_quicksort.c -o simple_quicksort

examples:
	./simple_quicksort this is a simple version of the quicksort algorithm

clean:
	rm -f simple_quicksort *~