OBJECTS=$(ROOT)/src/stla_timer.c $(ROOT)/src/stla_allocator.c $(ROOT)/src/stla_buffer.c $(ROOT)/src/stla_pool.c
HEADER_FILES=$(ROOT)/src/stla_common.h $(ROOT)/src/stla_timer.h $(ROOT)/src/stla_allocator.h $(ROOT)/src/stla_buffer.h $(ROOT)/src/stla_pool.h
FLAGS=-O3 -I$(ROOT)/src
