OBJECTS=$(ROOT)/src/actimer.c $(ROOT)/src/acallocator.c $(ROOT)/src/acbuffer.c $(ROOT)/src/acpool.c $(ROOT)/src/acmap.c $(ROOT)/src/acthreaded_pipe.c $(ROOT)/src/acasync_buffer.c $(ROOT)/src/accgi.c $(ROOT)/src/acconv.c $(ROOT)/src/achttp.c
HEADER_FILES=$(ROOT)/src/accommon.h $(ROOT)/src/actimer.h $(ROOT)/src/acallocator.h $(ROOT)/src/acbuffer.h $(ROOT)/src/acpool.h $(ROOT)/src/acmap.h $(ROOT)/src/acobject_pipe.h $(ROOT)/src/acthreaded_pipe.h $(ROOT)/src/acasync_buffer.h $(ROOT)/src/accgi.h $(ROOT)/src/acconv.h $(ROOT)/src/achttp.h
FLAGS=-O3 -I$(ROOT)/src
UV_OBJECTS=$(ROOT)/src/acobject_pipe.c
UV_HEADER_FILES=$(ROOT)/src/acobject_pipe.h
